version: '3.8'

volumes:
  demo_docker_db:

services:
  demo_docker_db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: demo_docker_db
    ports:
      - "5432:5432"
    volumes:
      - demo_docker_db:/var/lib/postgresql/data

  app:
    restart: always
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - demo_docker_db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://demo_docker_db:5432/demo_docker_db

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.6.1
    environment:
          ZOOKEEPER_CLIENT_PORT: 2181
          ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
      image: confluentinc/cp-kafka:7.4.4
      container_name: kafka
      depends_on:
        - zookeeper
      ports:
        - "9092:9092"
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ADVERTISED_HOST_NAME: localhost
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT